EXE := Game1.exe
CC := gcc
OUTDIR := build
INCLUDE := -Iinclude
SRC := src/*.c
LIBDIR := 
LIBS := -mwindows -lgdi32

.PHONY: clean_debug clean_debug_perf clean_release debug debug_perf release

FLAGS := -Wall -Wextra -Wpedantic -Wshadow -Wconversion -Wcast-align -Wformat=2 -Wfloat-equal -Wundef -Wcast-qual \
 -Wwrite-strings -Wstrict-overflow=5 -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wredundant-decls \
  -Wlogical-op -Winit-self -Wuninitialized -Wmaybe-uninitialized -Wstrict-prototypes -Wold-style-definition -Wsign-compare \
   -Wsign-conversion -Wjump-misses-init -Wstrict-aliasing=2 $(INCLUDE) $(SRC) $(LIBDIR) $(LIBS)

define build
	@del /Q $(OUTDIR)\$(1)\*.exe 2>NUL || exit 0
	@timeout /T 1 > NUL
	@if not exist $(OUTDIR)\$(1) mkdir $(OUTDIR)\$(1)
	$(CC) $(2) $(FLAGS) -o $(OUTDIR)/$(1)/$(EXE)
endef

debug:
	$(call build,debug,-D_DEBUG -O0 -g)

debug_perf:
	$(call build,debug_perf,-D_DEBUG -O2 -g)

release:
	$(call build,release,-O2 -s)